version: "3.8"

# =====================
# Services
# =====================
services:
  # Back-end .NET Container
  backend:
    container_name: backend
    ports:
      - 5000:5000
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - house-net
  
  # Front-end Nginx/Vue Container
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    restart: on-failure
    networks:
      - house-net


# ======================
# Docker Network
# ======================
networks:
  house-net:
    name: house-net
    external: false